- package.json
Updated dependency of mongodb nodejs driver to 1.4.26
We we're running into this issue when running on certain versions of MongoDB: https://jira.mongodb.org/browse/NODE-210
Updating to the latest mongodb nodejs driver solves the problem for us and allows all of our unit tests to complete successfully on all environments, regardless of MongoDB version on server.
> Fix for TypeError: Cannot call method isCompatible of null. 

- lib/connection.js
Fix typo in connection options (`numerOfRetries` -> `numberOfRetries`)
> Fix `numerOfRetries` -> `numberOfRetries` typo

- lib/query/index.js
Fix for parsing exception when filtering by date or datetime.
fixes #177 
fixes #1743 in "sails"
> Re-apply fix for #177 and add condition for 'datetime' type

- .travis.yml
- README.md
- test/integration/runner.js
~~Currently the build is broken and it always shows error: [![Build Status](https://travis-ci.org/balderdashy/sails-mongo.svg?branch=master)](https://travis-ci.org/balderdashy/sails-mongo), instead of "failing" / "passing". This PR fixes that by removing node 0.8 from travis.yml.~~
Additionally this PR adds:
* badges to the README;
* Integration tests: `failOnError: true`. so the build actually fails instead of wrongfully passing.
> Add badges and return non-zero if build breaks tests

- lib/document.js
This fixes an issue around creating records with specified mongo IDs.  In particular, this resolves an error that occurs when attempting to associate records during record creation.  See https://github.com/balderdashy/waterline/issues/908
The cloning step that used to happen here would clone a mongo ObjectId object, which would only happen incompletely due to the object's prototype.  In particular, it had its own `toString` method which was typically used to return the string representation of the mongo id.  Instead, you'd get `[object Object]` as an id!  D'oh!
CC @anasyb @particlebanana
> Remove cloning of ObjectID upon insert, etc.

- lib/collection.js
remove unnecessary cloneDeep circular structure when only one attribute is needed.
i kept the cloneDeep of attribute incase it would be needed somewhere.
fixes #253
> fix unnecessary cloneDeep circular structure

- lib/adapter.js
Ref: http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html
The idea here is to set the default mongo server settings in the adapter to the mongo driver's default settings.  Most notably, this does two things:
1. Set the TCP socket timeout to zero, which indicates that the socket connection to mongod should not timeout after a certain length of inactivity (i.e., making no queries).
2. Increase pool size to 5, which should allow for better default request concurrency and cover more use-cases out-of-the-box.
Hopefully this will resolve #266 #275 #276 – please test!
CC @dmarcelino @andypham
> Enforce driver server option defaults, no socket timeout.

- lib/collection.js
- lib/utils.js
Fixes #272 by processing the documents returned from MongoDB and replacing any mongo `Binary` for `Binary.buffer` thus satisfying waterline's expectations and passing the tests added in PR balderdashy/waterline-adapter-tests#66.
This PR has 2 commits:
1. refactored `.rewriteIds()` so we can re-use its inner logic in `.normalizeResults()`;
2. Adds `.normalizeResults()` to process mongodb documents and do the appropriate transformations.
Any feedback is welcomed!
As explained in #272:
> PR balderdashy/waterline-adapter-tests#66 exposes a bug in sails-mongo where binary type is not correctly saved and returned. The relevant test is: 
> ```javascript
>       it('should store proper binary value', function(done) {
>         // use a string
>         var str = 'test the things';
>         // to …
```
> Fix binary type returned by .find()

- .travis.yml
Since the build will run quicker as it won't have to install MongoDB 2.6.5.
> Travis: falling back to mongo 2.4

- lib/connection.js
Adding extra SSL configuration parameters for underlying mongodb driver to take advantage of so SSL certs/keys can be presented to mongo server and cert retrieved from mongo server can be compared/validated against a CA.
> Update connection.js Re: #323

- lib/adapter.js
- lib/utils.js
- package.json
- test/unit/utils.clarifyError.test.js
When the Mongo driver responds with an error during insertion and updates, intercept the error, examine the message, and, if the error is a result of a duplicate key constraint violation, produce a `WLValidationError`.
This is consistent with the implementations for the [sails-mysql](https://github.com/balderdashy/sails-mysql/blob/master/lib/adapter.js#L1201) and [sails-postgresql](https://github.com/balderdashy/sails-postgresql/blob/master/lib/adapter.js#L1215) adapters.
> Produce WLValidationError when a unique constraint is violated

- lib/adapter.js
This fixes case, when sails passes conn==null to adapter.teardown
and expects the adapter to tear down all connections:
https://github.com/balderdashy/sails/blob/faf92e321c9ddb9750720f5e6a405bbf15724a50/lib/hooks/orm/index.js#L219
> teardown: when conn==null, teardown all connections

- lib/connection.js
This tries to fix https://github.com/balderdashy/sails-mongo/issues/352
The db object assigned to connection key in (1) could actually have
it's field db assigned to undefined in (2), because the db object comes
from (5) (passed through (3), (4)) and it is actually is checked to be
undefined in (6), as returned from (5).
connections[connection.identity].connection = db;
https://github.com/balderdashy/sails-mongo/blob/659f430eaf1b7d2402d7762afaaf6bb78346d913/lib/adapter.js#L108
self.db = db;
https://github.com/balderdashy/sails-mongo/blob/659f430eaf1b7d2402d7762afaaf6bb78346d913/lib/connection.js#L28
this._buildConnection(function(err, db) {
https://github.com/balderdashy/sails-mongo/blob/659f430eaf1b7d2402d7762afaaf6bb78346d913/lib/connection.js#L24
MongoClient.connect(connectionString, …
> connection constructor: fix obscure case when both error and db are falsey

- lib/collection.js
Stream was only ended upon connection close, and not on stream ending.
> Handle stream `end` event.

- lib/query/index.js
- package.json
- test/unit/query/adapter.query.test.js
for the case : 
User.find({id:'56173df732776c64852f8c91'})
this would parse to query in the following (in mongodb.log):
query: { _id: ObjectId('56173804889cc73f952b7abd') } 
instead of :
query: { _id: ObjectId(/^56173804889cc73f952b7abd$/i) } 
This change improve  CRUD speed
> use validator to skip parsing mongoId to like query ,use direct query instead

- lib/collection.js
- test/unit/query/adapter.query.test.js
As the discussion in another issue balderdashy/waterline#805, I would suggest for an update operation, it's not needed to return the full updated result set. But even it's for compatibility reason we keep it, it should have an option to turn it off. At lease, if for now there's no plan to do it, we can use MongoDB projection when only fetching the needed `_id` field in the first find query
> Use MongoDB fields projection on update to reduce the memory footpints

- lib/utils.js
MapReduces results are like : 
```
{
'_id': {
'foo': "bar",
...
},
'values':{
'bar': "foo",
...
}
```
So when they're stringified, sails-mongo returned "[Object object]" string. Now fixed.
> Don't stringify IDs when not bson ObjectID

- lib/adapter.js
- lib/connection.js
Fixes reconnect issues with MongoDB, defaults now to 30 seconds.
It also adds reconnectTries, so you can configure both reconnectInterval and reconnectTries.
@nickerickson, @mudrekh and I found the issue about MongoDB not reconnecting. Basically, sails-mongo/lib/adapter.js sets reconnectInterval=200 and by default reconnectTries is 30, so, it just tries for 6 seconds. If the delay is more than 6 seconds, it will not retry.
> Fixes reconnect issues with MongoDB, defaults now to 30 seconds.

- lib/private/machines/find-records.js
This is probably the same as `.sort([])` -- testing indicates as much -- but just in case it's not, and for the purposes of fixing https://github.com/balderdashy/sails/issues/4105, no harm in removing the native sort method call altogether in these cases.
refs https://github.com/balderdashy/sails/issues/4105
> Skip running native `.sort()` if there's nothing to sort.

- lib/private/machines/sum-records.js
Hi guys, I found this bug in the code using the latest version of sails-mongo with the sum query:
```
/Users/josebalegarreta/Projects/kuaderno/teacher/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:123
process.nextTick(function() { throw err; });
^
TypeError: Cannot read property 'sum' of undefined
at aggregateCb (/Users/josebalegarreta/Projects/kuaderno/teacher/node_modules/sails-mongo/lib/private/machines/sum-records.js:80:38)
```
Basically if I do this query: `Connections.sum('time').where({student: student.id}).exec(next);` and if there're no connections that match that where condition, the mongo query result is an empty array instead of something like this: `[{_id: 'time', sum: 100}]`. So this part of code: `_.first(nativeResult).sum` crashes.
With this patch, if there no …
> Return 0 if there are no documents to sum

- lib/private/constants/config-whitelist.constant.js
Adding appname to config whitelist as shown on http://mongodb.github.io/node-mongodb-native/2.2/reference/connecting/connection-settings/
It is really important for us to be able to see what apps are using what connections by running `db.currentOp(true).inprog` on Mongo. Without appname configuration, this becomes very difficult in our environment.
> Adding missing appname to config whitelist

- lib/index.js
- lib/private/build-std-adapter-method.js
- lib/private/do-with-connection.js
- package.json
This simple little PR has `sails-mongo` basically working with [machine](https://github.com/node-machine/machine) v15.
All tests are passing, and a cursory run-through of different use-cases in our Sails apps show things to be functioning properly, at least.
The inspiration for switching to machine v15 is on the bug-fix front... Specifically, a rather troublesome memory-leak present in v13 is no more!
Without these patches up to v15 at least, it was necessary to remove `Debug()` calls from the v13 machine in order to achieve acceptable memory usage and avoid performance degradation. When the calls to `Debug()` remain, the result is an endlessly growing list of debug objects, sneakily hiding away from the GC, and that's no bueno.
**Disclaimer:** I'm not intimately familiar with the …
> Support machine 15

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- docker-compose.yml
- lib/private/machines/avg-records.js
- lib/private/machines/sum-records.js
Fix issue with aggregation with MongoDB version >=3.4. Now the cursor option is mandatory
> Fix issue with aggregation with MongoDB version >=3.4. Now the cursor option is mandatory

- lib/private/machines/private/build-mongo-where-clause.js
Option to make insensitive queries with like,
related suggest: #464 (comment) and
related on trello: https://trello.com/c/GHUSXlV1/185-i-want-to-be-able-to-toggle-case-sensitivity-on-or-off-for-like-contains-startswith-endswith-modifiers-in-my-where-clause
reference: https://docs.mongodb.com/manual/reference/operator/query/regex/
> added meta option makeLikeModifierCaseInsensitiveInMongo 

- .travis.yml
- CHANGELOG.md
- Dockerfile
- README.md
- appveyor.yml
- docker-compose.yml
- package.json
- scripts/appveyor/install_mongodb.ps1
- scripts/travis/install_mongodb.sh
- scripts/travis/run_mongodb.sh
- test/connectable/create-manager.test.js
- test/connectable/destroy-manager.test.js
- test/connectable/get-connection.test.js
- test/connectable/release-connection.test.js
- test/mocha.opts
- test/run-standard-tests.js
The idea here is to make sure the testing environment has the latest current and supported versions of Node and MongoDB.
With this, we can better review and clean up the other PRs associated to MongoDB driver upgrades.
My original PR (https://github.com/balderdashy/sails-mongo/pull/480) includes these changes. My intention is to separate that PR into two. This one should be addressed first.
Once this is done, the driver upgrade review would be easier.
My plan is to include/review all the driver PRs that have been proposed and create one based of them:
- https://github.com/balderdashy/sails-mongo/pull/483
- https://github.com/balderdashy/sails-mongo/pull/480
- https://github.com/balderdashy/sails-mongo/pull/472
- https://github.com/balderdashy/sails-mongo/pull/468
I'd appreciate the eyes …
> [patch] Several improvements to the test environment

- package.json
This fixes the standard adapter tests being skipped in the `custom-tests` script
> [patch] fix standard adapter tests

- package.json
Update async to fix npm audit issue
```
async  3.0.0 - 3.2.1
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install sails-mongo@1.2.0, which is a breaking change
node_modules/sails-mongo/node_modules/async
sails-mongo  >=2.0.0-0
Depends on vulnerable versions of async
node_modules/sails-mongo
```
Update MongoDB driver to 3.x.y latest with the same [compatibility](https://www.mongodb.com/docs/drivers/node/v3.7/compatibility/) for legacy MongoDB but also with better support for newer versions
> Update async 3.2.4, mongodb 3.7.3

- lib/private/constants/config-whitelist.constant.js
- package.json
Resolves https://github.com/balderdashy/sails/issues/7344
> [feat] add appName to whitelisted connection options
